name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Ajuste para a versão Python desejada

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Copy code to VM
      uses: google-github-actions/upload-cloud-storage@master
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}  # Configure suas credenciais do GCP como um segredo
        source: .  # Caminho para o diretório do seu código local
        destination: gs://bucker-jabot/bot-RU-telegram.zip  # Caminho no Cloud Storage onde você deseja armazenar o código ZIP
        args: -r  # Isso copiará todo o conteúdo recursivamente

    - name: Deploy to VM
      run: |
        # Conecte-se à sua VM do Google Compute Engine aqui e execute comandos para implantar o código
        # Exemplo: ssh user@ip-da-sua-vm 'comandos-de-deploy.sh'
      env:
        GCP_PROJECT_ID: silken-tenure-399322
        GCP_VM_INSTANCE: jabot-vm
        GCP_ZONE: us-central1-a  # Zona da sua VM
